export class DomainError extends Error {
  constructor(
    public code: string,
    message: string,
    public details?: Record<string, any>,
  ) {
    super(message);
    this.name = 'DomainError';
  }
}

export const ErrorCodes = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  BRANCH_SCOPE_DENIED: 'BRANCH_SCOPE_DENIED',
  CERTIFICATE_NOT_FOUND: 'CERTIFICATE_NOT_FOUND',
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
  COMPLETION_NOT_APPROVED: 'COMPLETION_NOT_APPROVED',
  PAYMENT_VALIDATION_FAILED: 'PAYMENT_VALIDATION_FAILED',
  DUPLICATE_ACTIVE_CERTIFICATE: 'DUPLICATE_ACTIVE_CERTIFICATE',
  CERTIFICATE_NUMBERING_UNAVAILABLE: 'CERTIFICATE_NUMBERING_UNAVAILABLE',
  VERIFICATION_CODE_CONFLICT: 'VERIFICATION_CODE_CONFLICT',
  CERTIFICATE_RENDER_FAILED: 'CERTIFICATE_RENDER_FAILED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  REISSUE_REASON_REQUIRED: 'REISSUE_REASON_REQUIRED',
  REISSUE_REASON_INVALID_LENGTH: 'REISSUE_REASON_INVALID_LENGTH',
  REISSUE_REQUEST_ALREADY_OPEN: 'REISSUE_REQUEST_ALREADY_OPEN',
  REISSUE_APPROVAL_REQUIRED: 'REISSUE_APPROVAL_REQUIRED',
  REISSUE_NOT_APPROVED: 'REISSUE_NOT_APPROVED',
  REVOCATION_REASON_REQUIRED: 'REVOCATION_REASON_REQUIRED',
  INVALID_OR_NOT_FOUND: 'INVALID_OR_NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SOURCE_REFERENCE_INCONSISTENT: 'SOURCE_REFERENCE_INCONSISTENT',
  COMPLETION_SERVICE_UNAVAILABLE: 'COMPLETION_SERVICE_UNAVAILABLE',
  PAYMENT_VALIDATION_UNAVAILABLE: 'PAYMENT_VALIDATION_UNAVAILABLE',
  VERIFICATION_STATUS_UNKNOWN: 'VERIFICATION_STATUS_UNKNOWN',
} as const;
